exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - package-lock.json
  - script
  - src

remote_theme: marella/jekyll-theme-documentation

title: cxzero training journey
owner_name: cxzero
owner_url: https://github.com/cxzero
x_url: https://twitter.com/cxzero

toc_min: 2
toc_max: 3

permalink: pretty
nav:
  - Introduction:
    - About: ''
  - HTB Cyber Apocalypse 2024:
    - web | LockTalk: content/ctf/htb/cyber-apocalypse-2024/web/LockTalk
    - web | SerialFlow: content/ctf/htb/cyber-apocalypse-2024/web/SerialFlow
    
